<h1 style="text-align:center; color:#005bbd; font-size:20px; font-family:Sans-serif; font-style: oblique; text-shadow: 0 0 3px white, 0 0 1px Black;">
   Primitive Data Types
</h1>

<body style="font-family: Sans-serif;">
    <div style="color: black; font-size: 15px; font-style: oblique; text-shadow: 0 0 3px white, 0 0 1px black; padding: 20px;">
        
Primitive Data Types woh basic aur fundamental data types hain jo kisi bhi programming language ke core building blocks hote hain.
        
Ye simple values store karte hain, complex structures nahi hote, aur directly memory allocate hoti hai.

- Primitive data types ka use fast aur efficient hota hai.
- Ye kisi bhi programming language mein pre-defined hote hain.
        
        
| **Data Type** | **Example Values** | **Description** |
|--------------|------------------|----------------|
| **Integer (int)** | `10, -5, 1000` | **Pure numbers** bina decimal ke |
| **Float (float)** | `3.14, -2.5, 0.99` | **Decimal values ya real numbers** |
| **Boolean (bool)** | `True, False` | **Binary values (1 or 0)** |
| **String (str)** | `"Hello", 'Python'` | **Text ya character sequence** |
| **Complex (complex)** | `3 + 4j, -2 - 1j` | **Real + Imaginary numbers (j unit ke sath)** |


<h1 style="text-align:center; color:#005bbd; font-size:20px; font-family:Sans-serif; font-style: oblique; text-shadow: 0 0 3px white, 0 0 1px Black;">
   Non-Primitive Data Types
</h1>

<body style="font-family: Sans-serif;">
    <div style="color: black; font-size: 15px; font-style: oblique; text-shadow: 0 0 3px white, 0 0 1px black; padding: 20px;">

**Non-Primitive Data Types** woh hote hain jo **multiple values ko store** karne ki capability rakhte hain.  
Ye **complex data structures** hote hain jo **primitive data types** ka combination bhi ho sakte hain.  
| **Data Type** | **Example Values** | **Description** |
|--------------|------------------|----------------|
| **List** | `[1, 2, 3]`, `["apple", "banana"]` | **Mutable ordered collection** |
| **Tuple** | `(10, 20, 30)`, `("a", "b")` | **Immutable ordered collection** |
| **Set** | `{1, 2, 3}`, `{"apple", "banana"}` | **Unordered unique values** |
| **Dictionary (dict)** | `{"name": "Ali", "age": 25}` | **Key-value pairs** |
| **String (str)** | `"Hello"`, `'Python'` | **Sequence of characters** |
| **Object (Class-based)** | `Custom class objects` | **User-defined data type** |


<h1 style="text-align:center; color:#005bbd; font-size:20px; font-family:Sans-serif; font-style: oblique; text-shadow: 0 0 3px white, 0 0 1px Black;">
   Arrays Data Structures
</h1>

<body style="font-family: Sans-serif;">
    <div style="color: black; font-size: 15px; font-style: oblique; text-shadow: 0 0 3px white, 0 0 1px black; padding: 20px;">

Arrays ek **`linear`** data structure hai jo same type ke elements ka **`contiguous memory`** mein storage provide karta hai. 

Iska use data ko efficiently store aur access karne ke liye hota hai.

<body style="font-family: Sans-serif;">
    <div style="color: black; font-size: 15px; font-style: oblique; text-shadow: 0 0 3px white, 0 0 1px black; padding: 20px;">
        
#### ***Linear Data Structure Kya Hota Hai?***
- Linear data structure ek aisa data organization method hai jisme elements sequence (line) mein store hote hain, aur unko order-wise access kiya jata hai.

<body style="font-family: Sans-serif;">
    <div style="color: black; font-size: 15px; font-style: oblique; text-shadow: 0 0 3px white, 0 0 1px black; padding: 20px;">
        
- #### 1️⃣ Sequential Order: 
    -  Data ek line-by-line store hota hai.

In [92]:
import numpy as np

In [94]:
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [95]:
for num in arr:
    print(num, end=" -> ")

10 -> 20 -> 30 -> 40 -> 50 -> 

<body style="font-family: Sans-serif;">
    <div style="color: black; font-size: 15px; font-style: oblique; text-shadow: 0 0 3px white, 0 0 1px black; padding: 20px;">
        
- #### 2️⃣ Single Level Access: 
    - Har element ka sirf ek previous aur ek next element hota hai (except first & last)

In [96]:
# Creating Linked List using Dictionary

class Node:
    def __init__(self, data):
        
        self.data = data
        self.next = None


In [97]:
# Creating Nodes

head = Node(10)

second = Node(20)

third = Node(30)

In [98]:
# Linking Nodes

head.next = second
second.next = third

In [99]:
head.data

10

In [100]:
head.next.data

20

In [101]:
head.next.next.data

30

In [102]:
current = head
while current:
    print(current.data, end=" -> ")
    current = current.next

10 -> 20 -> 30 -> 

<body style="font-family: Sans-serif;">
    <div style="color: black; font-size: 15px; font-style: oblique; text-shadow: 0 0 3px white, 0 0 1px black; padding: 20px;">
        
#### 3️⃣ Memory Utilization: 
- Ye contiguous (arrays) ya linked memory (linked lists) use kar sakta hai.

In [104]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [105]:
node1 = Node(1)
node2 = Node(2)
node1.next = node2 

In [106]:
 # Linked memory
import sys

print("Array Memory Size:", sys.getsizeof(arr))  # Fixed contiguous
print("Linked List Node Memory:", sys.getsizeof(node1))  # Dynamic

Array Memory Size: 152
Linked List Node Memory: 48


<body style="font-family: Sans-serif;">
    <div style="color: black; font-size: 15px; font-style: oblique; text-shadow: 0 0 3px white, 0 0 1px black; padding: 20px;">

- #### 4️⃣️⃣Traversal: 
    - Data ko start to end ya end to start traverse kiya ja sakta hai.

In [110]:
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [111]:
# Forward Traversal
print("Forward:", arr)

Forward: [10 20 30 40 50]


In [112]:
# Reverse Traversal
print("Reverse:", arr[::-1])

Reverse: [50 40 30 20 10]


<body style="font-family: Sans-serif;">
    <div style="color: black; font-size: 15px; font-style: oblique; text-shadow: 0 0 3px white, 0 0 1px black; padding: 20px;">

- #### 6️⃣ Fixed Size:
    - Array ka size initialize hone ke baad change nahi hota
    - Python mein built-in list dynamic hoti hai, magar agar array module ya NumPy array use karein, toh fixed-size behavior milta hai.

In [62]:
arr = [1,2,3]
arr

[1, 2, 3]

In [63]:
arr.insert(len(arr),4)

In [64]:
arr

[1, 2, 3, 4]

In [29]:
import numpy as np

In [66]:
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [68]:
arr.resize(3)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

<h1 style="text-align:center; color:#005bbd; font-size:20px; font-family:Sans-serif; font-style: oblique; text-shadow: 0 0 3px white, 0 0 1px Black;">
 Homogeneous vs Non-Homogeneous
</h1>

<body style="font-family: Sans-serif;">
    <div style="color: black; font-size: 15px; font-style: oblique; text-shadow: 0 0 3px white, 0 0 1px black; padding: 20px;">

#### 1️⃣ Homogeneous Data Structure        
    
-  Homogeneous ka matlab hai "same type ka data". 
- Iska matlab ye hai ke ek data structure sirf ek hi type ka data store karega, jaise sirf integers, sirf floats, ya sirf strings.
        
-  Ye data structures memory-efficient hote hain kyunki har element same type ka hota hai, is wajah se CPU fast processing karta hai.
- Example: NumPy Arrays, C Arrays, Stack (of same type elements), Queue (of same type elements)

-  ✅ Advantage: Fast execution, kam memory usage
- ❌ Disadvantage: Flexibility kam hoti hai (Sirf ek hi type ka data store ho sakta hai)

In [69]:
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr, type(arr))

[10 20 30 40] <class 'numpy.ndarray'>


In [72]:
np.array([10, 20, 30, 1.1]) # yaha 1.1 add karny sy sab float ho gaye

array([10. , 20. , 30. ,  1.1])

In [74]:
np.array([10, 20, 30, "A"]) # yaha A add karny sy sab string mein ho gaye

array(['10', '20', '30', 'A'], dtype='<U21')

<body style="font-family: Sans-serif;">
    <div style="color: black; font-size: 15px; font-style: oblique; text-shadow: 0 0 3px white, 0 0 1px black; padding: 20px;">
        
#### 2️⃣ Non-Homogeneous Data Structure
        
#### Non-homogeneous ka matlab hai "multiple types ka data". 
-  Iska matlab hai ke ek data structure alag-alag data types store kar sakta hai, jaise integers, strings, floats, booleans, etc.

- Ye data structures zyada flexible hote hain kyunki kisi bhi type ka data rakh sakte hain, lekin slow hote hain kyunki har element ka type check karna padta hai.
        
- Example: Python Lists, Tuples, Dictionaries, JSON Data

- ✅ Advantage: Zyada flexible, kisi bhi type ka data store kar sakta hai
- ❌ Disadvantage: Slow execution, zyada memory consume karta hai

In [75]:
mixed_list = [10, "Hello", 3.14, True]
mixed_list

[10, 'Hello', 3.14, True]

<h1 style="text-align:center; color:#005bbd; font-size:20px; font-family:Sans-serif; font-style: oblique; text-shadow: 0 0 3px white, 0 0 1px Black;">
 Static vs Dynamic
</h1>

<body style="font-family: Sans-serif;">
    <div style="color: black; font-size: 15px; font-style: oblique; text-shadow: 0 0 3px white, 0 0 1px black; padding: 20px;">
        
#### 1️⃣ Static Data Structures 
**Static Data Structure** woh hota hai jisme **size fixed hota hai** aur **pehle se define kiya jata hai**.  
Iska size program ke run hone se pehle allocate hota hai aur change nahi hota.  

**Features:**    
✅ Fixed size hota hai.  
✅ Memory pre-allocated hoti hai.  
✅ Fast execution kyunki data ek jagah stored hota hai.  
❌ Flexible nahi hota (size badal nahi sakta).  
❌ Agar extra memory allocate ho jaye jo use na ho, to wastage hoti hai.  

🔹 **Examples:**  
✔ **Arrays in C/C++**  
✔ **NumPy Arrays in Python**  
✔ **Static Stack & Static Queue**  

🔹 **Example (C Language Static Array)**
```c
int arr[5] = {10, 20, 30, 40, 50}; // Fixed-size array
arr[5] = 60;  // Error: Out of bounds
``` 
<br>
        
**Yahan error aayegi kyunki array ka size fixed hai (5 elements se zyada nahi ho sakta).**
        
- Python default mein dynamic memory allocation use karta hai, yani lists ka size automatically grow/shrink hota hai.
- Lekin NumPy arrays ka size fixed hota hai, yani ek dafa allocate hone ke baad change nahi hota.

In [88]:
arr = np.empty(3, dtype=int)
print(arr) 

[95437931203183              0             32]


In [89]:
arr[0] = 100
arr[1] = 200
arr[2] = 300

In [90]:
arr

array([100, 200, 300])

In [91]:
arr[3] = 400 # try to add more data

IndexError: index 3 is out of bounds for axis 0 with size 3

<body style="font-family: Sans-serif;">
    <div style="color: black; font-size: 15px; font-style: oblique; text-shadow: 0 0 3px white, 0 0 1px black; padding: 20px;">
        
2️⃣ Dynamic Data Structures 
        
**Dynamic Data Structure** woh hota hai jisme **size change ho sakta hai** aur **runtime par memory allocate hoti hai**.  
Iska size program ke chalne ke dauraan increase/decrease ho sakta hai.  

🔹 **Features:**  
✅ Size runtime par badal sakta hai.  
✅ Memory efficiently use hoti hai.  
✅ Insertion aur Deletion easily ho sakti hai.  
❌ Kabhi kabhi extra memory allocation ki wajah se fragmentation ho sakti hai.  
❌ Speed slow ho sakti hai kyunki pointers ka use hota hai.  

🔹 **Examples:**  
✔ **Python Lists (Dynamic)**  
✔ **Linked Lists**  
✔ **Dynamic Stacks & Queues**  
✔ **Heap Memory Allocation (`malloc` in C)**  

In [78]:
my_list = [10, 20, 30]  # Start with 3 elements
my_list.append(40)  # List ka size automatically badh gaya
print(my_list)  # [10, 20, 30, 40]

[10, 20, 30, 40]
